name: iris_health
description: Iris Health AI diagnostic app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shared_preferences: ^2.5.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Camera & image processing
  camera: ^0.11.3
  image: ^4.1.3

  # HTTP for AI server
  http: ^1.6.0
  http_parser: ^4.1.2
  archive: ^4.0.7
  file_selector: ^1.1.0
  mime: ^2.0.0
  path: ^1.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  camera_avfoundation: 0.9.22+9
