name: iris_health
description: Приложение для иридодиагностики с анализом глаз и историей обследований.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  http: ^1.5.0
  pdf: ^3.10.4
  intl: ^0.20.2
  permission_handler: ^12.0.1
  wakelock_plus: ^1.3.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cryptography: ^2.7.0
  tflite_flutter: ^0.11.0
  share_plus: ^11.1.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/models/quality.tflite
